### ISSUE TITLE
AUTH 504 5.7.4 Unrecognized authentication type connecting to outlook server

### ISSUE THREAD

**Issue by fridgerator** [raydf/smtp.cr#8]
here is my email code:

```crystal
EMail.send("smtp.office365.com", 587, use_tls: true, auth: {"username", "password"}) do
  subject "test stuff"
  from "test@test.com"
  to "test@test.com"

  message "test things"
end
```

and the output:

```
2017/07/10 15:12:07 [EMail_Client/66163] INFO Start TLS session
250-xxx.outlook.office365.com Hello [ip_address]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
504 5.7.4 Unrecognized authentication type [xxx.namprd02.prod.outlook.com]
2017/07/10 15:12:12 [EMail_Client/66163] ERROR <-- AUTH 504 5.7.4 Unrecognized authentication type [xxx.namprd02.prod.outlook.com]
2017/07/10 15:12:12 [EMail_Client/66163] ERROR Failed sending message for some reason
221 2.0.0 Service closing transmission channel
```

**Comment by ray-delossantos** [comment]
Hello @fridgerator, this library doesn't support TLS, please review this other shard: https://github.com/arcage/crystal-email; the only feature missing in that library is html templates i believe, that kind of feature takes more time because there should be code for inline attachments., maybe you could reach the author for further help.

Sorry that i can't help you more for this time, i hope later this year i'll have the time to merge both libraries into something better, or maybe as part of the std lib.

**Comment by fridgerator** [comment]
wow, I totally put this issue in the wrong repo...  thats embarrassing 

Sorry about that @raydf, can't believe I did that, lol
